.travis.yml, apns2/main.go
```
$ ./apns2 --help
usage: apns2 --certificate-path=CERTIFICATE-PATH --topic=TOPIC [<flags>]
Listens to STDIN to send nofitications and writes APNS response code and reason to STDOUT.
The expected format is: <DeviceToken> <APNS Payload>
Example: aff0c63d9eaa63ad161bafee732d5bc2c31f66d552054718ff19ce314371e5d0 {"aps": {"alert": "hi"}}
Flags:
--help               Show context-sensitive help (also try --help-long and --help-man).
-c, --certificate-path=CERTIFICATE-PATH
Path to certificate file.
-t, --topic=TOPIC        The topic of the remote notification, which is typically the bundle ID for your app
-m, --mode="production"  APNS server to send notifications to. `production` or `development`. Defaults to `production`
--version            Show application version.
```
=> Add command line tool `apns2`

client.go, client_test.go, notification.go, notification_test.go
We should not try to encode strings or byte arrays. We also shouldn't accept invalid json.
=> Fix Notification interface

client_test.go, response.go, response_test.go
- Fixes an issue where APNs timestamps were being parsed incorrectly.
- Removes some redundant code and tests.
APNs returns a Unix time with millisecond precision. We were parsing and not
accounting for the milliseconds, which was giving an invalid Time. This has been
tested on APNs production gateway and now parses and returns the correct Time.
=> Fix Timestamp parsing issue

README.md
ApnsID of response structire is string type not function.
Please refer to: https://github.com/sideshow/apns2/blob/master/response.go#L86
cc @sideshow
=> Fix apns id Type

README.md
It's from the example, and if one was to copy the README verbatim, they'd get the error `res declared and not used`
=> Include printing of APNS ID in example

payload/builder.go, payload/builder_test.go
Missing set `loc-args` property.
ref: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW1
=> Add AlertLocArgs method.

client.go, client_test.go
This is a fix for #17 and #20 
Its a cherrypick of the @c3mb0 pull request in #22 without the retry code and with configurable timeout globals for HTTPClientTimeout and TLSDialTimeout
=> Fix timeout

payload/builder.go, payload/builder_test.go
Add support for the new iOS 10 Notification Services extensions. More details [here](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension).
Fixes #27
=> Add support for the mutable-content flag 

README.md, _example/main.go
First off, awesome library!
I added this into my project and everything was working great. But when I went to switch over to production, I just removed the `.Development()` and assumed the default host would be production (my bad... never assume). I think replacing the `Development` with `Production` in the example would clarify this and help future developers from making the same mistake.
=> Change example to reflect production

response.go
Fix for issue #34 where `strconv.Atoi()` on a 32bit build was giving `value out of range` error.
=> Fix value out of range issue #34

client.go, client_test.go, notification.go
When displaying notifications, the system visually groups notifications
with the same thread identifier together.
Fixes #40
=> Add iOS10 thread-id to notification

response.go
- Fixes #48 by adding the missing constants, and also updates the rest
of the status codes and descriptions to be the same as Table 8-6 in the
Apple docs.
=> Add missing Reason constants

client.go, client_test.go, notification.go, payload/builder.go, payload/builder_test.go
Fixes issue #61 by removing thread-id from the Notification struct.
You now add a thread-id to the aps payload as per Apple docs.
See https://github.com/sideshow/apns2/pull/41#issuecomment-266804527 for discussion.
=> Fix incorrect thread-id implementation

.travis.yml, client_manager.go, client_manager_test.go
Variation of @dwieeb and @xjewer PR's. Keeps the existing API, and doesn't limit to just one ClientManager. 
- Fixes issue #58
=> Fix issue 58

client.go
Adds TCP Keepalive default of 60 seconds.
This prevents an issue on AWS (and potentially Google Cloud) where they will terminate the connection after a period of time unless it has TCP Keeplaive enabled or there is data being sent when using a NAT instance.
Before:
After:
=> Add TCP Keepalive

client.go, client_test.go
Adds a CloseIdleConnections method to close the underlying tcp connections. 
This can be helpful when you dispose of the apns2 client, to make sure that the underlying TCP connections are disposed of.
=> Add CloseIdleConnections method to close tcp connections

README.md
Small change to make the readme a bit more friendly. I was caught up by this for a few minutes, before realizing that I had to use `payload.NewPayload`.
=> Update readme with correct usage of payload.NewPayload.

.gitignore, certificate/certificate_test.go
Changes tests to pass on go1.11 as VerifyHostname returns an error. Instead we now check that the certificate returned is not a blank one.
=> Fix VerifyHostname certificate validation on go1.11

client.go, client_test.go
Check error of http request creation
=> fix(panic) fix client push panic

client_test.go, notification.go
Adds remainder of `apns-push-type` types. According to Apple docs there are 6 possible values. https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
=> Add remainder of EPushType types

client.go, token/token.go
We cannot refer to `t.Bearer` during `t.Generate` because we changed it during `t.Generate`.
=> fix data race

README.md, payload/builder.go, payload/builder_test.go
- Adds interruption-level to payload
interruption-level options:
- passive
- active (default if none is passed to apns)
- time-sensitive
- critical (requires Apple entitlement)
- Adds relevance-score to payload
- Updates readme re iOS 15 features
=> Add iOS 15 payload additions

README.md, client_test.go, notification.go, response.go
- Add support for [location push type](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/) for [location push service extensions](https://developer.apple.com/documentation/corelocation/cllocationmanager/creating_a_location_push_service_extension) 
- Add InvalidPushType reason error code
=> Add location push type

client.go, client_test.go
It's also has lower allocations since request created with context immediately, instead of recreating request WithContext.
=> Use NewRequestWithContext

client.go
Avoid fmt.Sprintf, maybe for some business applications it's make sense, but for efficient libraries, to my mind, it's better to avoid it, especially in hot paths.
=> Use appropriate type cast functions

client.go
Pointer to pointer passed to json Decode instead of plain pointer to struct. Standard JSON library pretty smart aware of it, but it results in unneeded allocation of reflect.Type/Kind highly likely internally in encoding/json.
=> Fix double pointer in Decode call

client_test.go, notification.go, payload/builder.go, payload/builder_test.go
This is a revision of https://github.com/sideshow/apns2/pull/217 which addresses the pull request comments there and also adds support for `stale-date` as documented at https://developer.apple.com/documentation/activitykit/updating-and-ending-your-live-activity-with-activitykit-push-notifications
=> Live Activity support added (revised and expanded)

certificate/certificate.go, certificate/certificate_test.go, token/token.go, token/token_test.go
Updates `ioutil.ReadFile` to `os.ReadFile`
Fixes https://github.com/sideshow/apns2/issues/229
=> Update ioutil.ReadFile to os.ReadFile

client.go, client_test.go, notification.go
Hi
First of all thanks for the effort on this great library.
Currently i have some usage on push to talk which required the push type of pushtotalk.
it would be great if you can merge the following changes.
Thanks!
Eric
=> Support pushtotalk type push notification
